#!/bin/sh

# Download, compile, and copy the vcprompt command to ~/bin.
#
# AUTHOR: Geoffrey Grosenbach
#         July 27 2009

mkdir -p ~/src
cd ~/src
hg clone http://hg.gerg.ca/vcprompt/
cd vcprompt
autoconf
./configure
make
cp vcprompt ~/bin/vcprompt
